### ISSUE TITLE
Processing of MD file never ends.

### ISSUE THREAD

**Issue by robertjank** [wheleph/nttt#34]
Project Guide to my county 1.0, languages nl-NL, de-DE and ja-JP. Processing of step_12.md never ends and has to be stopped with Ctrl-C. This results in the following stacktrace on Windows:
```
Traceback (most recent call last):
  File "C:\Users\Robert-Jan\AppData\Local\Programs\Python\Python38\Scripts\nttt-script.py", line 11, in <module>
    load_entry_point('nttt===0.1.1-SNAPSHOT', 'console_scripts', 'nttt')()
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\__init__.py", line 9, in main
    tidyup_translations(resolved_arguments)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\tidyup.py", line 116, in tidyup_translations
    fix_step(source_file_path, language, output_file_path, disable)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\tidyup.py", line 57, in fix_step
    content = trim_spaces_on_specific_markdown(content)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\cleanup_markdown.py", line 66, in trim_spaces_on_specific_markdown
    if bool(re.search(regular_expressions_matrix_for_trimming_spaces[i]['regular_expression_for_correct'], modified_string)):
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\re.py", line 198, in search
    def search(pattern, string, flags=0):
KeyboardInterrupt
```
and on Linux:
```
Traceback (most recent call last):
  File "/home/robertjan/.local/bin/nttt", line 8, in <module>
    sys.exit(main())
  File "/home/robertjan/.local/lib/python3.8/site-packages/nttt/__init__.py", line 9, in main
    tidyup_translations(resolved_arguments)
  File "/home/robertjan/.local/lib/python3.8/site-packages/nttt/tidyup.py", line 116, in tidyup_translations
    fix_step(source_file_path, language, output_file_path, disable)
  File "/home/robertjan/.local/lib/python3.8/site-packages/nttt/tidyup.py", line 57, in fix_step
    content = trim_spaces_on_specific_markdown(content)
  File "/home/robertjan/.local/lib/python3.8/site-packages/nttt/cleanup_markdown.py", line 66, in trim_spaces_on_specific_markdown
    if bool(re.search(regular_expressions_matrix_for_trimming_spaces[i]['regular_expression_for_correct'], modified_string)):
  File "/usr/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.8/re.py", line 292, in _compile
    return _cache[type(pattern), pattern, flags]
KeyboardInterrupt
```

**Comment by robertjank** [comment]
Project Frustration, language de-DE. Processing of step_1.md never ends and has to be stopped with Ctrl-C. This results in the following stacktrace on Windows:
```
Traceback (most recent call last):
  File "C:\Users\Robert-Jan\AppData\Local\Programs\Python\Python38\Scripts\nttt-script.py", line 11, in <module>
    load_entry_point('nttt===0.1.1-SNAPSHOT', 'console_scripts', 'nttt')()
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\__init__.py", line 9, in main
    tidyup_translations(resolved_arguments)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\tidyup.py", line 116, in tidyup_translations
    fix_step(source_file_path, language, output_file_path, disable)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\tidyup.py", line 57, in fix_step
    content = trim_spaces_on_specific_markdown(content)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\cleanup_markdown.py", line 66, in trim_spaces_on_specific_markdown
    if bool(re.search(regular_expressions_matrix_for_trimming_spaces[i]['regular_expression_for_correct'], modified_string)):
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\re.py", line 291, in _compile
    if isinstance(flags, RegexFlag):
KeyboardInterrupt
```

**Comment by robertjank** [comment]
Project Rock, Paper, Scissors, language pl-PL. Processing of step_1.md never ends and has to be stopped with Ctrl-C. This results in the following stacktrace on Windows:

```
Traceback (most recent call last):
  File "C:\Users\Robert-Jan\AppData\Local\Programs\Python\Python38\Scripts\nttt-script.py", line 11, in <module>
    load_entry_point('nttt===0.1.1-SNAPSHOT', 'console_scripts', 'nttt')()
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\__init__.py", line 9, in main
    tidyup_translations(resolved_arguments)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\tidyup.py", line 116, in tidyup_translations
    fix_step(source_file_path, language, output_file_path, disable)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\tidyup.py", line 57, in fix_step
    content = trim_spaces_on_specific_markdown(content)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\site-packages\nttt\cleanup_markdown.py", line 66, in trim_spaces_on_specific_markdown
    if bool(re.search(regular_expressions_matrix_for_trimming_spaces[i]['regular_expression_for_correct'], modified_string)):
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "c:\users\robert-jan\appdata\local\programs\python\python38\lib\re.py", line 291, in _compile
    if isinstance(flags, RegexFlag):
KeyboardInterrupt
```
